### ISSUE TITLE
💡 [REQUEST] - Copie d'écran dans le README

### ISSUE THREAD

**Issue by arthurzenika** [cloud-pi-native/console#1115]
### Description

Pour se faire une idée sur le projet une copie d'écran dans le README serait la bienvenue.

### Définition du fini

- [ ] La fonctionnalité est terminée
- [ ] Les tests liés à cette fonctionnalité ont été ajoutés
- [X] La documentation liée à cette fonctionnalité a été ajoutée (cf. https://github.com/cloud-pi-native/documentation)
- [ ] La communication avec les autres équipes impliquées par cette fonctionnalité a été faite

**Comment by this-is-tobi** [comment]
fixed in #1131
