### ISSUE TITLE
🐛 [BUG] - Mauvaise gestion d'erreur lors de la sync des repositories

### ISSUE THREAD

**Issue by thomashbrnrd** [cloud-pi-native/console#1118]
### Description

Le retour du frontend lors de la sync d'un repo via la console DSO n'est pas correctement géré. Un message popup "succès" vert apparait quelque soit l'état final du call API. J'ai testé en mettant un nom de branch inexistant, et en coupant le VPN ou internet, et le message de succès apparait à chaque fois, même si le call API fail.

### Etapes de reproduction

```bash
1. Aller sur la console.
2. Aller dans un projet.
3. Aller sur la page d'un repository dans l'onglet "Synchronisation"
4. Couper internet et lancer la syncho, un message de succès apparait, alors que le call API a échoué.
```

### Captures d'écran

```bash
![DESCRIPTION](LINK.png)
```

### Navigateurs

Chrome

### OS

Windows

### Définition du fini

- [ ] Le correctif est terminé
- [ ] Les tests liés à ce correctif ont été ajoutés
- [ ] La communication avec les autres équipes impliquées par ce correctif a été faite

**Comment by clairenollet** [comment]
Hello ! Merci pour l'issue.

J'ai modifié le message. En fait on lance le pipeline de synchro, on n'attend pas qu'il réussisse ou qu'il échoue pour renvoyer une réponse. Mais le message porte à confusion.
![image](https://github.com/cloud-pi-native/console/assets/71137721/a4921eeb-5beb-4d79-8eb6-a0af8f2c9b38)
![image](https://github.com/cloud-pi-native/console/assets/71137721/673b6945-d789-41fd-bb5b-e0f6daaaa0cf)
