### ISSUE TITLE
🐛 [BUG] - Interface qui n'est pas claire

### ISSUE THREAD

**Issue by rouja** [cloud-pi-native/console#1144]
### Description

L'interface pour la suppression d'un projet n'est pas claire et porte à confusion. On se demande si ça va bien supprimer le projet ainsi que le projet côté openshift ou si ça va archiver

### Etapes de reproduction

```bash
1. Se connecter à la console
2. Cliquer sur 'projets' puis 'Mes projets'
3. Sélectionner un projet
4. Puis cliquer sur 'Supprimer ce projet'
```

### Captures d'écran

![2024-05-30_22-24](https://github.com/cloud-pi-native/console/assets/22145127/f9aaed89-f76c-4441-9def-585c271166c2)

### Version de la console impactée

v8.4.0

### Définition du fini

- [ ] Le correctif est terminé
- [ ] Les tests liés à ce correctif ont été ajoutés
- [ ] La communication avec les autres équipes impliquées par ce correctif a été faite

**Comment by this-is-tobi** [comment]
- Remplacer les dernière occurence de `Archiver` pour `Supprimer`.
- Ajouter un texte qui explique que le suppression du projet entraine la suppression de toutes les ressources applicatives (namespace, ...)
