### ISSUE TITLE
Afficher les informations de déploiement à l'utilisateur

### ISSUE THREAD

**Issue by plec** [cloud-pi-native/console#147]
### US
ETQ Owner de repo, je souhaite consulter les informations de déploiement de mon projet, au moins le namespace sur sur lequel il peut déployer l'application. Et permettre à l'utilisateur de réafficher cette information dans la console. afin de créer mes fichiers de déploiement ArgoCD
Suite à l'onboarding des projets, il faudrait aussi avoir l'information du GITLAB TRIGGER TOKEN qui permet de lancer la synchro des repos

## TODO
Afficher sur le dashboard : 
- NAMESPACE => `<organization>-<nom-projet>-<nom-environnement>`
- GITLAB_TRIGGER_TOKEN

**Comment by clairenollet** [comment]
cf #140

**Comment by plec** [comment]
Suite à l'onboarding des projets, il faudrait aussi avoir l'information du GITLAB TRIGGER TOKEN qui permet de lancer la synchro des repos

**Comment by clairenollet** [comment]
## Pour lister les hosts des ingress :

```
kubectl get --all-namespaces ingress -o json 2> /dev/null| jq -r '.items[] | .spec.rules[] | .host as $host | .http.paths[] | ( $host + .path)' | sort | grep -v ^/ 
```

**Comment by clairenollet** [comment]
fixed by #644
