### ISSUE TITLE
Intégration api Canel2

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#261]
## TODO

- [x] déterminer données à transmettre à partir du swagger https://github.com/dnum-mi/canel2/blob/main/api/static/api-canel.yml
- [x] appeler api à chaque CUD sur projet

## Dependancies

https://github.com/orgs/dnum-mi/projects/15/views/1?pane=issue&itemId=22125477

**Comment by ArnaudTa** [comment]
à déplacer vers le plugin cible

**Comment by this-is-tobi** [comment]
Done in https://github.com/dnum-mi/dso-console-canel-plugin
