### ISSUE TITLE
Outil de migration des données

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#265]
# US
ETD je souhaite que mes données soient adaptées automatiquement par mon ORM lorsque je fais évoluer mon schéma de bdd.

### Dans un premier temps

- [x] parcourir les docs des différents outils de migration
- [x] tester leur implémentation
- [x] faire un petit benchmark

## Prisma

- [x] Prisma Migrate -> Migration automatique de la BDD. Fonctionne en commande
- [x] Prisma Client -> Lancer la vérification des données lorsque l'application démarre
- [x] Remplacer les models Sequelize par Prisma
- [x] Remplacer les queries Sequelize par Prisma
- [x] Tests -> Modifier les tests en conséquence

## Ressources

https://www.prisma.io/docs/concepts/components/prisma-migrate
https://www.prisma.io/docs/concepts/components/prisma-client

**Comment by this-is-tobi** [comment]
Done in #439
