### ISSUE TITLE
Pouvoir demander des quotas de ressources

### ISSUE THREAD

**Issue by this-is-tobi** [cloud-pi-native/console#270]
## US

En tant qu'utilisateur je souhaite pouvoir assigner / faire évoluer les quotas (cpu, ram, stockage ? + type de stockage ?) de mon projet pour chacun de mes environnements.

## Tech

- [x] Ajout des champs pour spécifier des quotas dans le formulaire de création d'environnement (+ possibilité de modifier ces quotas)

### à réfléchir
- [x] Table `quotas` ~contenant un `environmentId`~
- [ ] ~Un `quota` par `environment`~
- [x] 4 quotas de départ écrits en base, chaque `environment` référence un `quotaId`
- [x] Créer des flavors (utiliser un slider)
  - small (S): 2vcpu / 4Gb ram (dev, qualif, preprod, prod) 
  - medium (M): 4vcpu / 8Gb ram (dev, qualif, preprod, prod)
  - large (L): 6vcpu / 12Gb ram (preprod, prod)
  - extraslarge (XL): 8vcpu / 16Gb ram (preprod, prod)
- [x] Afficher un message expliquant que si le projet souhaite dépasser les flavors, il doit contacter les administrateurs

**Comment by clairenollet** [comment]
![Image](https://github.com/cloud-pi-native/console/assets/71137721/5c087c11-2ff2-44e3-adf3-96e7deac3520)
