### ISSUE TITLE
Pouvoir accéder au formulaire de création du .gitlab-ci-dso en dehors de la création d'un repo

### ISSUE THREAD

**Issue by this-is-tobi** [cloud-pi-native/console#333]
ETU je souhaite pouvoir créer le fichier `.gitlab-ci-dso` à l'aide du formulaire de la console y compris lorsque je ne créé pas un dépôt

**Comment by clairenollet** [comment]
Tu veux : 
- Avoir accès au formulaire au clic sur un repo déjà créé ?
- Avoir accès au formulaire hors dépôt (les valeurs internalRepoName etc. seront vides) ?

**Comment by this-is-tobi** [comment]
> @this-is-tobi tu veux :
> 
> * Avoir accès au formulaire au clic sur un repo déjà créé ?
> * Avoir accès au formulaire hors dépôt (donc les valeurs internalRepoName etc. seront vides) ?

Plutôt la première option alors je pense

**Comment by this-is-tobi** [comment]
Done in #486
