### ISSUE TITLE
Mettre à jour les templates de gitlab-ci pour harbor

### ISSUE THREAD

**Issue by this-is-tobi** [cloud-pi-native/console#366]
La chaine DSO intégrant à partir de la `v3.0.0` Harbor à la place de Quay comme registry, il convient de mettre à jour des templates de `.gitlab-ci` généré par la console pour qu'ils fonctionnent avec Harbor

**Comment by clairenollet** [comment]
je le met en todo ça @this-is-tobi ?

**Comment by this-is-tobi** [comment]
> je le met en todo ça @this-is-tobi ?

En vrai ça a été fait mais on va les remettre à jour donc on peut caler en `todo` oui !

**Comment by this-is-tobi** [comment]
Done in #466
