### ISSUE TITLE
Amélioration UX création dépôt d'infra

### ISSUE THREAD

**Issue by this-is-tobi** [cloud-pi-native/console#434]
## US

ETU je souhaite lors de la création d'un dépôt d'infrastructure pouvoir renseigner des informations supplémentaires pour argocd :
- Le dossier dans lequel se trouvent les `manifestes kubernetes` ou les `templates helm`
- La `branche` ou le `tag` utilisé par l'application argo

ETU je souhaite pouvoir choisir quel environnement est synchronisé / build / déployé

**Comment by clairenollet** [comment]
Ce sont des données qu'on doit envoyer dans la bdd ? Je modifie le modèle etc ? @this-is-tobi @ArnaudTA

**Comment by this-is-tobi** [comment]
@clairenollet au final on va rester générique (au moins pour quelques temps) et laisser les gens modifier ces infos directement dans Argocd
