### ISSUE TITLE
[admin page log] bug suivant / précédent logs

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#476]
# Bug
quand on clique sur `voir les logs suivants` on a la liste des logs précédents + suivants et pas que les suivants (ex 10 logs au lieu de 5 page 2). Vient sans doute de la fonction `showLogs`

**Comment by ArnaudTA** [comment]
C'est une feature on va dire, il suffit de renommer le bouton "charger plus"
Arnaud TARDIF.



13 juin 2023, 18:24 de ***@***.***:
