### ISSUE TITLE
Afficher les tokens lors de la création de son projet

### ISSUE THREAD

**Issue by this-is-tobi** [cloud-pi-native/console#566]
ETU je souhaite pouvoir voir les tokens générés lorsque je créé un projet : 
- token Gitlab
- token Sonarqube
- token Harbor ?

# tech

- [x] remonter les infos contenues dans `project.services` dans une zone dédiée sur le `DsoDashboard.vue`
- [x] ajouter un bouton "Voir les secrets"
- [x] ce bouton déclenche un appel api qui appelle un `hook` pour récupérer les tokens contenus dans Vault
- [x] stocker les `tokens` de chaque plugin dans Vault

**Comment by clairenollet** [comment]
on les voit une fois à la création puis plus jamais (comme sur github quand on crée un token) ? Ou on peut les voir tout le temps ?

**Comment by clairenollet** [comment]
- `token gitlab` => `triggerToken.token` ?
- `token harbor` => `robot.secret` ?

**Comment by clairenollet** [comment]
> on les voit une fois à la création puis plus jamais (comme sur github quand on crée un token) ? Ou on peut les voir tout le temps ?

pour le moment tout le temps car pas de procédure pour recréer facilement les tokens

**Comment by ArnaudTA** [comment]
```
kv/
  org1/
    project1/
      services/
        [nom du service]/
          TOKEN = "abc"
          USER = "truc"
```

quand le user demande à afficher les secrets
on get tout ce qui est dans services et on lui affiche

- création d'un bouton demande d'afficher les secrets du projet
- création d'un point d'API
- création d'un hook getProjectSecrets
- réécriture des plugins pour adapter le chemin de stockage
- afficher le retour d'API dans un tableau

**Comment by clairenollet** [comment]
On n'affiche que `gitlab` pour l'instant, à discuter pour le reste
