### ISSUE TITLE
💡 [REQUEST] - backoffice admin

### ISSUE THREAD

**Issue by clairenollet** [cloud-pi-native/console#815]
### Description

ETAdmin je souhaite avoir accès à un backoffice me permettant d'effectuer des actions sur les projets :

- [x] déterminer quelles actions les admins ont le droit de faire sur un projet

**Comment by ArnaudTA** [comment]
Proposition de spec et de vue
![image](https://github.com/cloud-pi-native/console/assets/33383276/75a56702-7b21-4508-82a0-7bb02be8ad0a)
![image](https://github.com/cloud-pi-native/console/assets/33383276/8a819c8e-885c-4b22-83fa-8349a2db3431)
