### ISSUE TITLE
[Bug] Majuscule sur le nom logique des repos

### ISSUE THREAD

**Issue by plec** [cloud-pi-native/console#833]
Lors de la création d'un repo synchronisé on lui donne un nom logique et il est possible de mettre une majuscule, par exemple "Documentation". Si on fait cela, cela génère une erreur lors de la création de l'application dans ArgoCD : 

{"response":{"statusCode":422,"body":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Application.argoproj.io \"mi-service-team-dev-Documentation-6293\" is invalid: metadata.name: Invalid value: \"mi-service-team-dev-Documentation-6293\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"mi-service-team-dev-Documentation-6293","group":"argoproj.io","kind":"Application","causes": [...]

il faudrait soit on interdire les majuscules lors de la saisie du nom logique du repo ou forcer tout en minuscule avant l'enregistrement.

**Comment by this-is-tobi** [comment]
fixed in #834 
Available in release `6.2.0`
